{
    'name': 'School Management System',
    'version': '1.0',
    'category': 'Education',
    'summary': 'School Management',
    'author': 'RMA Cambodia',
    'license': 'LGPL-3',

    'depends': [
        'base',
        'mail',
        'purchase',
        'base_automation',
        'contacts',
        'product',
        'report_xlsx',
    ],

    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/mail_template.xml',
        'data/mail_purchase_request.xml',
        'data/mail_student_enrollment.xml',
        'data/server_action.xml',
        'data/automated_action.xml',
        'reports/purchase_request_templates.xml',
        'reports/purchase_request_report.xml',
        'security/record_rules.xml',
        'views/student_registry_views.xml',
        'views/student_course_views.xml',
        'views/department_views.xml',
        'views/teacher_views.xml',
        'views/school_setting_views.xml',
        'views/batch_views.xml',
        'views/time_table_slot_views.xml',
        'views/academic_program_views.xml',
        'views/academic_year_views.xml',
        'views/academic_year_level_views.xml',
        'views/school_major_views.xml',
        'views/class_group_views.xml',
        'views/room_views.xml',
        'views/school_curriculum_views.xml',
        'views/school_enrollment_views.xml',
        'views/purchase_request_views.xml',
        'views/res_partner_views.xml',
        'views/purchase_order_views.xml',
        'views/purchase_analysis_report_views.xml',
        'views/menu.xml',
    ],
    'assets': {
            'web.assets_backend': [
                'school_management_system/static/src/css/timetable_calendar.css',
            ],
        },
    'application': True,
    'installable': True,
}