from . import student_registry
from . import course
from . import department
from . import teacher
from . import academic_year
from . import school_setting
from . import academic_program
from . import school_academic_year_level
from . import class_group
from . import batch
from . import school_schedule
from . import school_schedule_line
from . import school_schedule_session
from . import room
from . import school_major
from . import school_curriculum
from . import school_enrollment
from . import purchase_request
from . import purchase_request_line
from . import res_partner
from . import purchase_order
from . import purchase_analysis_report

