from . import student_registry, course
from . import department
from . import teacher
from . import academic_year
from . import school_setting
from . import academic_program
from . import school_academic_year_level
from . import class_group
from . import batch
from . import school_schedule
from . import school_schedule_line
from . import school_schedule_session
from . import room
from . import school_major
from . import school_curriculum
from . import school_enrollment
from . import purchase_request
from . import purchase_request_line
from . import school_vendors
from . import purchase_order
from . import purchase_analysis_report
from . import school_attendace
from . import school_products
from . import school_payment
from . import school_curriculum_price